# 参考配置地址：https://hexo.fluid-dev.com/docs/guide
navbar:
  blog_title: Yang Fanbin

dark_mode:
  enable: true
  default: light

index:
  slogan:
    enable: true
    text: 山山而川 不过尔尔

  auto_excerpt:
    enable: false  # 文章摘要开关

favicon: /assets/img/favicon.ico

banner_img: /assets/img/top.png
