name: Build & Deploy Hexo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_DIR: repo  # 仓库克隆到的基础目录
      BLOG_DIR: ${{ env.REPO_DIR }}/Blog  # 仓库内部的Blog目录路径
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_OBSIDIAN_TOKEN }}
          repository: 'mmungdong/my-obsidian'
          path: ${{ env.REPO_DIR }}  # 克隆到repo目录（而非直接克隆到Blog）

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          working-directory: ${{ env.BLOG_DIR }}  # 指向仓库内部的Blog目录

      - name: Install deps & build
        run: |
          git config --global user.name 'my-obsidian actions'
          git config --global user.email 'github@action.com'
          git remote add pages https://x-access-token:${{ secrets.MMUNGDONG_GITHUB_IO_PUSH }}@github.com/mmungdong/mmungdong.github.io.git
          npm ci
          npm install
          npx hexo clean
          npx hexo generate
          npx hexo deploy
        working-directory: ${{ env.BLOG_DIR }}  # 确保在仓库内部的Blog目录执行命令
        env:
          HEXO_DEPLOY_TOKEN: ${{ secrets.MMUNGDONG_GITHUB_IO_PUSH }}
